version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      dev-dependencies:
        patterns:
          - '*'
        dependency-type: development
