/** Canonical constitution metadata for G-002 publishing. */

export const ADRS = [
  {
    id: 'ADR-0001',
    title: 'Monorepo with Turborepo',
    status: 'Accepted',
    related: ['MBC v1.1.0', 'CEC §3.2', 'EAP Deliverable 1', 'EDS §9'],
  },
  {
    id: 'ADR-0002',
    title: 'PostgreSQL as primary OLTP',
    status: 'Accepted',
    related: ['MBC §5', 'CEC §5', 'EAP Deliverable 5', 'EDS §5'],
  },
  {
    id: 'ADR-0003',
    title: 'Schema-per-tenant multi-tenancy',
    status: 'Accepted',
    related: ['MBC §6.3', 'CEC §5.11', 'EAP Deliverable 5', 'EDS §1.2'],
  },
  {
    id: 'ADR-0004',
    title: 'NestJS for domain microservices',
    status: 'Accepted',
    related: ['CEC §4', 'EAP Deliverable 2', 'EDS §1'],
  },
  {
    id: 'ADR-0005',
    title: 'Next.js 15 App Router for web',
    status: 'Accepted',
    related: ['MBC §25', 'CEC §6', 'EAP Deliverable 11'],
  },
  {
    id: 'ADR-0006',
    title: 'React Native + Expo for mobile',
    status: 'Accepted',
    related: ['CEC §2.2', 'EAP Deliverable 11'],
  },
  {
    id: 'ADR-0007',
    title: 'Apache Kafka for event fabric',
    status: 'Accepted',
    related: ['MBC Phase 0.1 §2', 'CEC §4.9', 'EAP Deliverable 4', 'EDS §7'],
  },
  {
    id: 'ADR-0008',
    title: 'Kubernetes on AWS EKS primary',
    status: 'Accepted',
    related: ['MBC §10', 'CEC §8', 'EAP Deliverable 7', 'EDS §9'],
  },
  {
    id: 'ADR-0009',
    title: 'Keycloak for identity plane',
    status: 'Accepted',
    related: ['MBC §8', 'CEC §4.7', 'EAP Deliverable 8', 'EDS §1.1'],
  },
  {
    id: 'ADR-0010',
    title: 'RBAC + ABAC + ReBAC hybrid',
    status: 'Accepted',
    related: ['MBC §8.3', 'MBC §15', 'CEC §10', 'EAP Deliverable 8'],
  },
  {
    id: 'ADR-0011',
    title: 'OpenSearch for full-text search',
    status: 'Accepted',
    related: ['MBC Phase 0.1 §15', 'EAP Deliverable 2', 'EDS §1.8'],
  },
  {
    id: 'ADR-0012',
    title: 'Azure OpenAI primary LLM',
    status: 'Accepted',
    related: ['MBC §9', 'CEC §7', 'EAP Deliverable 6', 'EDS §1.10'],
  },
  {
    id: 'ADR-0013',
    title: 'Cursor-based API pagination',
    status: 'Accepted',
    related: ['MBC Phase 0.1 §3', 'CEC §4.15', 'EAP Deliverable 3'],
  },
  {
    id: 'ADR-0014',
    title: 'Conventional Commits',
    status: 'Accepted',
    related: ['MBC Phase 0.1 §6', 'CEC §3.6'],
  },
  {
    id: 'ADR-0015',
    title: 'LaunchDarkly for feature flags',
    status: 'Proposed',
    related: ['MBC Phase 0.1 §6.6', 'EAP §1.10'],
  },
  {
    id: 'ADR-0016',
    title: 'GraphQL federation at v6.0',
    status: 'Proposed',
    related: ['MBC Phase 0.1 §3.7', 'EAP Deliverable 3'],
  },
  {
    id: 'ADR-0017',
    title: 'pgvector for embeddings',
    status: 'Accepted',
    related: ['MBC Phase 0.1 §8', 'EAP Deliverable 6', 'EDS §1.8', 'EDS §1.10'],
  },
  {
    id: 'ADR-0018',
    title: 'Cloudflare R2 for object storage',
    status: 'Proposed',
    related: ['MBC §29', 'EAP §1.11', 'EDS §1.4'],
  },
  {
    id: 'ADR-0019',
    title: 'SearchOS as independent bounded context',
    status: 'Accepted',
    related: ['MBC Phase 0.1 §15', 'EAP Deliverable 2', 'EDS §1.8'],
  },
  {
    id: 'ADR-0020',
    title: 'RFC 7807 Problem Details for all APIs',
    status: 'Accepted',
    related: ['MBC Phase 0.1 §3.5', 'CEC §4.15', 'EAP Deliverable 3'],
  },
  {
    id: 'ADR-0021',
    title: 'Bun as monorepo package manager',
    status: 'Accepted',
    related: ['ADR-0001', 'CEC §3.2', 'G-001 Repository Foundation', 'EDS §15 FF-PERF-006'],
  },
];

export const MBC_SECTIONS = [
  {
    part: 'PART I — CONSTITUTIONAL FOUNDATIONS',
    items: [
      '§1 Constitutional Principles',
      '§2 Scope Definition',
      '§3 Product Vision (2035)',
      '§4 Business Architecture',
      '§5 Enterprise Architecture Framework',
    ],
  },
  {
    part: 'PART II — PLATFORM ARCHITECTURE',
    items: [
      '§6 Platform Architecture',
      '§7 Governance Architecture',
      '§8 Security Architecture',
      '§9 AI Architecture',
      '§10 DevOps Architecture',
      '§11 Observability Architecture',
      '§12 Scalability Architecture',
      '§13 Documentation Architecture',
    ],
  },
  {
    part: 'PART III — IDENTITY, ROLES & PERMISSIONS',
    items: ['§14 Complete Role Registry', '§15 Permission Constitution'],
  },
  {
    part: 'PART IV — MODULE REGISTRY',
    items: [
      '§16 Module Taxonomy',
      '§17 Module Specification Template',
      '§18 CORE DOMAIN',
      '§19 PEOPLE DOMAIN',
      '§20 FINANCE DOMAIN',
      '§21 CAMPUS DOMAIN',
      '§22 GROWTH DOMAIN',
      '§23 ENGAGEMENT DOMAIN',
      '§24 PLATFORM DOMAIN',
      '§25 EXPERIENCE DOMAIN',
    ],
  },
  {
    part: 'PART V–IX',
    items: [
      '§26 Governance Domain',
      '§27 Future & Innovation (2030–2035)',
      '§28 CommunicateOS',
      '§29 ContentOS',
      '§30 ServiceOS',
      '§31 IntegrationOS',
      '§32 Operational Model',
      '§33 Compliance Architecture',
      '§34 Master Roadmap',
      '§35 Version Summary Matrix',
    ],
  },
  {
    part: 'PART X — APPENDICES',
    items: [
      'Appendix A: 85 Modules',
      'Appendix B: Constitutional KPIs',
      'Appendix C: Risk Register',
      'Appendix D: Glossary',
    ],
  },
  {
    part: 'PHASE 0.1 ADDITIONS (v1.1.0)',
    items: [
      '§1 ADR Process',
      '§2 Event Catalog',
      '§3 API Constitution',
      '§4 UI/UX Constitution',
      '§5 Design System',
      '§6 Platform Engineering',
      '§7 Data Architecture',
      '§8 AI Expansion',
      '§9 Security Expansion',
      '§10 Reliability',
      '§11 Observability',
      '§12 Marketplace',
      '§13 Workflow Engine',
      '§14 Globalization',
      '§15 SearchOS',
      '§16 Notifications',
      '§17 Billing',
      '§18 Testing',
      '§19 Documentation',
      '§20 Governance Boards',
      '§21 Product Analytics',
      '§22 Phase Gates',
      '§23 Phase 1 Readiness',
    ],
  },
];

export const CEC_SECTIONS = [
  '§1 Engineering Principles',
  '§2 Coding Standards',
  '§3 Repository Constitution',
  '§4 Backend Constitution',
  '§5 Database Constitution',
  '§6 Frontend Constitution',
  '§7 AI Engineering Constitution',
  '§8 DevOps Constitution',
  '§9 Testing Constitution',
  '§10 Security Engineering',
  '§11 Performance Constitution',
  '§12 Documentation Constitution',
  '§13 Engineering Checklists',
  '§14 Engineering KPIs',
  '§15 Engineering Governance',
];

export const EAP_DELIVERABLES = [
  'Deliverable 1 — Enterprise Architecture (C4, Domains, Dependencies)',
  'Deliverable 2 — Service Catalog',
  'Deliverable 3 — API Constitution (Enterprise Binding)',
  'Deliverable 4 — Event Architecture',
  'Deliverable 5 — Data Architecture',
  'Deliverable 6 — AI Architecture',
  'Deliverable 7 — Infrastructure Architecture',
  'Deliverable 8 — Security Architecture',
  'Deliverable 9 — Observability Architecture',
  'Deliverable 10 — Performance Architecture',
  'Deliverable 11 — Frontend Architecture',
  'Deliverable 12 — Integration Architecture',
  'Deliverable 13 — Marketplace Architecture',
  'Deliverable 14 — Operational Architecture',
  'Deliverable 15 — Enterprise Quality Architecture',
  'Deliverable 16 — Documentation Standards',
  'Deliverable 17 — Enterprise Diagrams',
  'Deliverable 18 — Constitutional Additions',
  'Deliverable 19 — Final Readiness Expansion',
  'Deliverable 20 — Final Ratification Package',
];

export const EDS_SECTIONS = [
  '§1 Complete Service Specifications',
  '§2 Component Diagrams',
  '§3 Internal Sequence Diagrams',
  '§4 Entity Lifecycle Diagrams',
  '§5 Data Ownership Matrix',
  '§6 Bounded Context Interaction Matrix',
  '§7 Detailed Event Catalog Expansion',
  '§8 API Dependency Map',
  '§9 Infrastructure Topology',
  '§10 Capacity Planning',
  '§11 Threat Surface Mapping',
  '§12 Disaster Recovery Design',
  '§13 Observability Design',
  '§14 Enterprise Runbook Design',
  '§15 Architecture Fitness Functions',
  '§16 Operational Readiness',
  '§17 Cross-References',
  '§18 Constitutional Additions',
];

export const REQUIRED_DOCS = [
  'docs/constitution/README.md',
  'docs/constitution/MBC/CAMPUSOS-MBC-001-v1.1.0.md',
  'docs/constitution/CEC/CAMPUSOS-CEC-001-v1.0.0.md',
  'docs/constitution/EAP/CAMPUSOS-EAP-001-v1.0.0.md',
  'docs/constitution/EDS/CAMPUSOS-EDS-001-v1.0.0.md',
  'docs/constitution/ADR/README.md',
  'docs/constitution/versions/README.md',
];
